services:
  - type: web
    name: daily-log-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    disk:
      name: temp-storage
      mountPath: /tmp
      sizeGB: 1
    request:
      timeout: 300
      bodySizeLimit: 100mb
