services:
  - type: web
    name: daily-log-ai
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    disk:
      name: temp-storage
      mountPath: /tmp
      sizeGB: 1
    headers:
      - source: /*
        headers:
          - key: Content-Length
            value: 0
    request:
      timeout: 300
      bodySizeLimit: 100mb
